// AUTH TYPES
export const USER_AUTH = "USER_AUTH";
export const USER_LOGOUT = "USER_LOGOUT";

// CART TYPES
export const CART_ADD = "CART_ADD";
export const CART_REMOVER = "CART_REMOVE";

// PRODUCT TYPES
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
