// USER TYPES
export const USER_AUTH = "USER_AUTH";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_UPDATE = "USER_UPDATE";
export const GET_ALL_USERS = "GET_ALL_USERS";

// CART TYPES
export const CART_ADD = "CART_ADD";
export const CART_REMOVER = "CART_REMOVE";

// PRODUCT TYPES
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const REMOVE_SINGLE_PRODUCT = "REMOVE_SINGLE_PRODUCT";
export const TOGGLE_SINGLE_PRODUCT_LOADING = "TOGGLE_SINGLE_PRODUCT_LOADING";
